package co.edu.usbcali.demo.modelo;
// Generated 22/04/2016 07:50:35 PM by Hibernate Tools 4.0.0

/**
 * ConsignacionesId generated by hbm2java
 */
public class ConsignacionesId implements java.io.Serializable {


}
