package co.edu.usbcali.demo.modelo;
// Generated 22/04/2016 07:50:35 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * Consignaciones generated by hbm2java
 */
public class Consignaciones implements java.io.Serializable {
	
	@NotNull
	private long conCodigo;

	@NotNull
	private String cueNumero;

	@NotNull
	private Usuarios usuarios;
	
	private Cuentas cuentas;
	
	@NotNull
	private BigDecimal conValor;
	
	@NotNull
	private Date conFecha;
	
	@NotNull
	private String conDescripcion;

	public Consignaciones() {
	}

	public Consignaciones(long conCodigo, String cueNumero, Cuentas cuentas, BigDecimal conValor, Date conFecha,
			String conDescripcion) {
		this.conCodigo = conCodigo;
		this.cuentas = cuentas;
		this.conValor = conValor;
		this.conFecha = conFecha;
		this.conDescripcion = conDescripcion;
	}

	public Consignaciones(long conCodigo, String cueNumero, Usuarios usuarios, Cuentas cuentas, BigDecimal conValor, Date conFecha,
			String conDescripcion) {
		this.conCodigo = conCodigo;
		this.cueNumero = cueNumero;
		this.usuarios = usuarios;
		this.cuentas = cuentas;
		this.conValor = conValor;
		this.conFecha = conFecha;
		this.conDescripcion = conDescripcion;
	}


	public long getConCodigo() {
		return this.conCodigo;
	}

	public void setConCodigo(long conCodigo) {
		this.conCodigo = conCodigo;
	}

	public String getCueNumero() {
		return this.cueNumero;
	}

	public void setCueNumero(String cueNumero) {
		this.cueNumero = cueNumero;
	}


	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public BigDecimal getConValor() {
		return this.conValor;
	}

	public void setConValor(BigDecimal conValor) {
		this.conValor = conValor;
	}

	public Date getConFecha() {
		return this.conFecha;
	}

	public void setConFecha(Date conFecha) {
		this.conFecha = conFecha;
	}

	public String getConDescripcion() {
		return this.conDescripcion;
	}

	public void setConDescripcion(String conDescripcion) {
		this.conDescripcion = conDescripcion;
	}

}
