package co.edu.usbcali.demo.modelo;
// Generated 22/04/2016 07:50:35 PM by Hibernate Tools 4.0.0

/**
 * RetirosId generated by hbm2java
 */
public class RetirosId implements java.io.Serializable {





}
